include:
  # Extend default template with some Oxeva custom configurations for a NodeJS webapp project
  - project: 'cloud/gitlab-ci'
    ref: master
    file: '/templates/nginx-website/nginx.gitlab-ci.yml'

variables:
  REVIEW_LAB_ENABLED: 1

staging:
  stage: deploy
  tags:
    - cloud-dev
