backend:
  name: github
  repo: MargotDem/website-netlify
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: contentfulPage
    label: "Contentful Page"
    folder: "/static/content/pages/contentfulPages"
    create: true
    fields:
      - name: "metaData"
        label: "Meta Data"
        widget: "object"
        fields:
          - { name: "path", label: "Path" }
          - { name: "title", label: "Title" }
          - { name: "description", label: "Description", widget: "text", required: false }
          - name: "image"
            label: "Image"
            widget: "object"
            required: false
            fields:
              - { name: "imagePath", label: "Image Path", widget: "image" }
              - { name: "imageAlt", label: "Image Alt", widget: "string" }
          - { name: "openGraphType", label: "Open Graph Type", widget: "hidden", default: "website" }
          - { name: "twitterCard", label: "Twitter Card", widget: "hidden", default: "summary" }
      - {label: "Page Type", name: "pageType", widget: "hidden", default: "contentfulPage"}
      - { name: "title", label: "Title" }
      - name: "contents"
        label: "Contents"
        widget: "list"
        fields:
        - label: "Content Types Widget"
          name: "contentTypesWidget"
          widget: "contentTypesWidget"
          fields:
            - name: simpleContent
              label: "Simple Content"
              widget: "object"
              fields:
                - { name: title, label: Title }
                - { name: description, label: Description, widget: markdown }
                - name: "image"
                  label: "Image"
                  widget: "object"
                  required: false
                  fields:
                    - { name: "imagePath", label: "Image Path", widget: "image" }
                    - { name: "imageAlt", label: "Image Alt", widget: "string" }
            - name: "text"
              label: "Text"
              widget: "object"
              fields:
                - { name: "title", label: "Title" }
                - { name: "text", label: "Text", widget: "text"}
      - { label: "Date", name: "lastmod", widget: "hiddenDate" }
  - name: simplePage
    label: "Simple Page"
    folder: "/static/content/pages/simplePages"
    create: true
    fields:
      - name: "metaData"
        label: "Meta Data"
        widget: "object"
        fields:
          - { name: "path", label: "Path" }
          - { name: "title", label: "Title" }
          - { name: "description", label: "Description", widget: "text", required: false }
          - name: "image"
            label: "Image"
            widget: "object"
            required: false
            fields:
              - { name: "imagePath", label: "Image Path", widget: "image" }
              - { name: "imageAlt", label: "Image Alt", widget: "string" }
          - { name: "openGraphType", label: "Open Graph Type", widget: "hidden", default: "website" }
          - { name: "twitterCard", label: "Twitter Card", widget: "hidden", default: "summary" }
      - {label: "Page Type", name: "pageType", widget: "hidden", default: "simplePage"}
      - { name: title, label: Title }
      - { name: body, label: Description, widget: markdown }
      - { label: "Date", name: "lastmod", widget: "hiddenDate" }
  - name: "singleElements"
    label: "Single Elements"
    delete: false
    files:
      - name: header
        label: Header
        file: "/static/content/header.md"
        fields:
          - { name: title, label: Title }
          - name: sections
            label: Sections
            widget: list
            fields:
              - { name: title, label: Title }
              - name: linkPath
                label: LinkPath
                required: false
              - name: links
                label: Links
                widget: list
                required: false
                fields:
                  - { name: linkName, label: LinkName }
                  - { name: linkPath, label: LinkPath }
      - name: footer
        label: Footer
        file: "/static/content/footer.md"
        fields:
          - { name: title, label: Title }
          - name: sections
            label: Sections
            widget: list
            fields:
              - { name: title, label: Title }
              - name: links
                label: Links
                widget: list
                fields:
                  - { name: linkName, label: LinkName }
                  - { name: linkPath, label: LinkPath }
      - name: "homePage"
        label: "Home Page"
        file: "/static/content/homePage.md"
        fields:
          - { name: title, label: Title }
          - name: "contents"
            label: "Contents"
            widget: "list"
            fields:
              - name: "content"
                label: "Content"
                widget: "relation"
                collection: "content"
                searchFields: ["title"]
                valueField: "title"